version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock